project:
  type: book
  output-dir: _book

book:
  # book
  title: "Non-Cooperative Games"
  author: "John Forbes Nash"
  date: "1950-05"
  downloads: [pdf]
  repo-url: https://github.com/luifrancgom/non-cooperative_games_nash/
  issue-url: https://github.com/luifrancgom/non-cooperative_games_nash/issues
  repo-actions: [edit, source, issue]
  reader-mode: true
  chapters:
    - index.qmd
    - abstract.qmd
    - introduction.qmd
    # - formal_definitions_and_terminology.qmd
    # - existence_of_equilibrium_points.qmd
    # - symmetries_of_games.qmd
    # - solutions.qmd
    # - geometrical_form_of_solutions.qmd
    # - dominance_and_contradiction_methods.qmd
    # - a_three-man_poker_game.qmd
    # - motivation_and_interpretation.qmd
    # - applications.qmd
    - references.qmd
    - acknowledgements.qmd

format:
  html:
    # table of contents
    toc: true
    toc-location: right
    # rendering
    embed-resources: false
    # format options
    theme:
      - cosmo
      - scss/custom.scss
    html-math-method: mathjax
  pdf:
    # format options
    pdf-engine: xelatex
    # table of contents
    toc: true
    # fonts
    fontsize: 11pt
    # colors
    linkcolor: blue
    citecolor: blue
    urlcolor: blue
    colorlinks: true
    # layout
    documentclass: scrbook
    papersize: a4
    indent: true
    # references
    link-citations: true
    link-bibliography: true

bibliography: references/non-cooperative_games.bib
csl: references/apa_7ed.csl

engine: knitr
editor: source